version: '3.8'

services:
  # GROBID service for PDF metadata extraction
  grobid:
    image: lfoppiano/grobid:0.8.0
    container_name: kg-grobid
    ports:
      - "8070:8070"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/api/isalive"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Main pipeline service
  pipeline:
    build:
      context: .
      target: app
    container_name: kg-pipeline
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - GROBID_URL=http://grobid:8070/api/processFulltextDocument
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./streamlit_app:/app/streamlit_app
    working_dir: /app
    command: python src/run_pipeline.py
    restart: on-failure
    depends_on:
      grobid:
        condition: service_healthy

  # Streamlit visualization service
  streamlit:
    build:
      context: .
      target: streamlit
    container_name: kg-streamlit
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
    volumes:
      - ./data:/app/data
      - ./streamlit_app:/app/streamlit_app
      - ./src:/app/src
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - pipeline
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3

# Named volumes for persistent data
volumes:
  kg_data:
    driver: local
  kg_output:
    driver: local

# Network for service communication
networks:
  default:
    name: kg-network
    driver: bridge