services:
  pipeline:
    build:
      context: .
      target: app
    container_name: kg-pipeline
    network_mode: "host"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - GROBID_URL=http://localhost:8070/api/processFulltextDocument
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./streamlit_app:/app/streamlit_app
    working_dir: /app
    command: python src/run_pipeline.py
    restart: on-failure

  # Streamlit visualization service
  streamlit:
    build:
      context: .
      target: streamlit
    container_name: kg-streamlit
    network_mode: "host"
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
    volumes:
      - ./data:/app/data
      - ./streamlit_app:/app/streamlit_app
      - ./src:/app/src
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - pipeline